# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe '10xBookingImport' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '10xBookingImport' do
    @driver.get('http://ec2-52-87-156-42.compute-1.amazonaws.com:3000/')
    @driver.find_element(:css, '.icon-reorder').click
    @driver.find_element(:link_text, 'Administration').click
    @driver.find_element(:css, '.imports > li:nth-child(3) .dashboard-item-label').click
    @driver.find_element(:xpath, '//a[contains(@href, \'/easy_entity_imports/25\')]').click
    @driver.find_element(:name, 'attachments[dummy][file]').click
    @driver.find_element(:name, 'attachments[dummy][file]').send_keys('/home/dayalan/Downloads/PSA 10.x imports - Booking (1) .csv')
    @driver.find_element(:name, 'button').click
    @driver.find_element(:css, '.icon-magnifier:nth-child(1)').click
    dropdown = @driver.find_element(:id, 'easy_entity_import_merge_by')
    dropdown.find_element(:xpath, "//option[. = 'ID']").click
    dragged = @driver.find_element(:css, 'big[data-name=ID]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_easy_external_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'ERM Project ID\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_project_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'Tracker ID\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_tracker_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=Status]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_status_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'ERM User Id\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_assigned_to_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'Task Name\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_subject_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'startdate\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_start_date_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'enddate\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_due_date_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'ERM Task_Id\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_parent_issue_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'ERM User Id\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_author_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'hours\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_estimated_hours_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'ID\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    @driver.find_element(:css, '.icon-import').click
  end
end
