# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe '10xInvoiceHeaderImport' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '10xInvoiceHeaderImport' do
    @driver.get('http://ec2-52-87-156-42.compute-1.amazonaws.com:3000/')
    @driver.find_element(:css, '.icon-reorder').click
    @driver.find_element(:link_text, 'Administration').click
    @driver.find_element(:css, '.imports > li:nth-child(3) .dashboard-item-label').click
    @driver.find_element(:xpath, '//a[contains(@href, \'/easy_entity_imports/27\')]').click
    @driver.find_element(:name, 'attachments[dummy][file]').click
    @driver.find_element(:name, 'attachments[dummy][file]').send_keys('/home/dayalan/Downloads/PSA 10.x imports - Invoices Header (3).csv')
    @driver.find_element(:name, 'button').click
    @driver.find_element(:css, '.icon-magnifier:nth-child(1)').click
    element = @driver.find_element(:name, 'button')
    @driver.action.move_to_element(element).perform
    dropdown = @driver.find_element(:id, 'easy_entity_import_merge_by')
    dropdown.find_element(:xpath, "//option[. = 'ID']").click
    dragged = @driver.find_element(:css, 'big[data-name=id]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_easy_external_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=id]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=invoice_number]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_number_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=date]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_issued_at_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'Due Date\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_due_at_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=Comment]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_note_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=Amount]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_total_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'ERM Customer_id\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_client_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=\'ERM Project_id\']')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_project_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=Easy_Invoice_status]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_easy_invoice_status_id_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=Invoice_Type]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_type_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=PSA_Approval_status]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_aurea_status_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    dragged = @driver.find_element(:css, 'big[data-name=Invoice_Type]')
    dropped = @driver.find_element(:css, 'input[id=easy_entity_import_attribute_cf_18_value]')
    @driver.action.drag_and_drop(dragged, dropped).perform
    @driver.find_element(:css, '.icon-import').click
  end
end
