# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Psaimportdraganddropprojects10xfinal' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'psaimportdraganddropprojects10xfinal' do
    @driver.get('http://ec2-3-87-152-18.compute-1.amazonaws.com:3000/easy_entity_imports/11')
    @driver.find_element(:name, 'attachments[dummy][file]').click
    @driver.find_element(:name, 'attachments[dummy][file]').send_keys('/home/dayalan/Downloads/PSA 10.x imports - Projects (1).csv')
    @driver.find_element(:name, 'button').click
    element = @driver.find_element(:name, 'button')
    @driver.action.move_to_element(element).perform
    @driver.find_element(:css, '.icon-magnifier:nth-child(1)').click
    dropdown = @driver.find_element(:id, 'easy_entity_import_merge_by')
    dropdown.find_element(:xpath, "//option[. = 'ID']").click
    element = @driver.find_element(:id, 'easy_entity_import_merge_by')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:id, 'easy_entity_import_merge_by')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:id, 'easy_entity_import_merge_by')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'easy_entity_import_merge_by').click
    element = @driver.find_element(:css, 'li:nth-child(2) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'ol > li:nth-child(2)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'ol > li:nth-child(2)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(37) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'li:nth-child(36)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'li:nth-child(36)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(6) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'ol > li:nth-child(5)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'ol > li:nth-child(5)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(33) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'li:nth-child(32)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'li:nth-child(32)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(33) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'li:nth-child(33)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'li:nth-child(33)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(6) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'ol > li:nth-child(7)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'ol > li:nth-child(7)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(33) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'li:nth-child(32)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'li:nth-child(32)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft').click
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(4) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'ol > li:nth-child(5)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'ol > li:nth-child(5)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(10) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '.ui-droppable-hover > label:nth-child(1)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '.ui-droppable-hover > label:nth-child(1)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(3) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(7) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_att_cf_22 > .easy-entity-import-attribute-form-field')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_att_cf_22 > .easy-entity-import-attribute-form-field')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(9) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'ol > li:nth-child(8)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'ol > li:nth-child(8)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(11) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'ol > li:nth-child(11)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'ol > li:nth-child(11)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(8) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'ol > li:nth-child(9)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'ol > li:nth-child(9)')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(8) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '#easy_entity_import_mappings > .splitcontentleft')
    @driver.action.move_to_element(element).release.perform
    element = @driver.find_element(:css, 'li:nth-child(36) > .easy-import-child')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'li:nth-child(35)')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'li:nth-child(35)')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:css, '.icon-import').click
  end
end
